// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable()
class User {
  String? id;
  num? estado;

  User({this.id, this.estado});
  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
  Map<String, dynamic> toJson() => _$UserToJson(this);
}

class Users {
  List<User> items = List<User>.empty();

  Users();

  Users.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final result = new User.fromJson(item);
      items.add(result);
    }
  }
}
