import 'package:flutter/material.dart';

List preferences = [
  {
    "name": "Guerra",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Guerra2.jpg",
    "status": false,
  },
  {
    "name": "Costumbre",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Costumbres.jpg",
    "status": false,
  },
  {
    "name": "Alimento",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Alimento.jpg",
    "status": false,
  },
  {
    "name": "Funeraria",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Funeraria.jpg",
    "status": false,
  },
  {
    "name": "Herramientas",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Herramientas.jpg",
    "status": false,
  },
  {
    "name": "Historia",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Historia.jpg",
    "status": false,
  },
  {
    "name": "Vestimenta",
    "color1": Color.fromARGB(100, 0, 0, 0),
    "color2": Color.fromARGB(100, 0, 0, 0),
    "color1Activate": Color.fromARGB(0, 0, 0, 0),
    "color2Activate": Color.fromARGB(0, 0, 0, 0),
    "img": "assets/Vestimenta.jpg",
    "status": false,
  },
];
